stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CIBW_BUILD: cp39-*
  CIBW_ARCHS: x86_64

before_script:
  - curl -sSL https://get.docker.com/ | sh
  - python -m pip install cibuildwheel==2.21.3 build

build_wheels:
  stage: build
  image: python:3.12
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/

build_sdist:
  stage: build
  image: python:3.12
  script:
    - python -m build --sdist --outdir dist
  artifacts:
    paths:
      - dist/*.tar.gz