image: python:3.9

stages:
  - build

variables:
  CIBW_BUILD: "cp39-*"
  CIBW_SKIP: "cp27-* pp*"
  CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2010"

before_script:
  - pip install cibuildwheel==2.3.0

build_wheels:
  stage: build
  script:
    - cibuildwheel --output-dir wheelhouse
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 1 week