stages:
  - build
  - test
  - release

variables:
  FORCE_COLOR: "3"

default:
  before_script:
    - git submodule update --init --recursive

concurrency:
  group: $CI_PIPELINE_ID
  cancel-in-progress: true

build_sdist:
  stage: build
  image: python:3.9
  script:
    - pip install pipx
    - pipx install build
    - pipx run build --sdist
    - pipx install twine
    - pipx run twine check dist/*
  artifacts:
    paths:
      - dist/*.tar.gz
    expire_in: 1 week

build_wheels:
  stage: build
  parallel:
    matrix:
      - OS: "ubuntu-latest"
      - OS: "macos-13"
      - OS: "macos-latest"
      - OS: "windows-latest"
  script:
    - pip install pipx
    - pipx install cibuildwheel
    - CIBW_PRERELEASE_PYTHONS=true CIBW_ARCHS_WINDOWS="auto ARM64" pipx run cibuildwheel --output-dir wheelhouse
    - git diff --exit-code
  artifacts:
    paths:
      - wheelhouse/*.whl
    expire_in: 1 week