[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "example_package_JonSnowPatrol"
version = "0.1.8"
authors = [
  { name="Anton Rikus", email="a.rikus@uni-muenster.de" },
]
description = "A fresh example package - now using pybind and openMP!"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[tool.scikit-build]
messages.after-success = "{green}Wheel successfully built! Hooray!"
messages.after-failure = """
{bold.red}Sorry{normal}, build failed. Your platform is {platform.platform}. Better luck next time!
"""
build.verbose = true
logging.level = "INFO"
build-dir = "/WORK/a_riku01/PyPI/packaging_tutorial/skbuild/"

[tool.scikit-build.cmake.define]
HDF5_ROOT="/usr/local/h5"
USEBOOST = false
USEHDF5 = false

[tool.cibuildwheel]
build-verbosity = 1
# Only build on CPython 3.9
build = "cp39-*"

[tool.cibuildwheel.linux]
# yum install -y boost-devel hdf5-devel
#wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/#hdf5-1.12.0/src/hdf5-1.12.0.tar.bz2
#tar --bzip2 -xf hdf5-1.12.0.tar.bz2
#cd hdf5-1.12.0
#./configure --prefix=/usr/local/h5 --enable-cxx
#make -j 8
#make install -j 8
#cd ..
#export PATH=/usr/local/h5/bin:$PATH
#which h5c++
#h5cc -showconfig
before-all = """
yum install -y wget tar bzip2
"""
archs = ["x86_64"]
skip = ["*-musllinux_x86_64"]

# the yum command is not available on the musllinux image
[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add boost-dev"