[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "example_package_JonSnowPatrol"
version = "0.1.4"
authors = [
  { name="Anton Rikus", email="a.rikus@uni-muenster.de" },
]
description = "A fresh example package - now using pybind and openMP!"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[tool.scikit-build]
messages.after-success = "{green}Wheel successfully built! Hooray!"
messages.after-failure = """
{bold.red}Sorry{normal}, build failed. Your platform is {platform.platform}. Better luck next time!
"""
build.verbose = true
logging.level = "INFO"

[tool.cibuildwheel]
build-verbosity = 1
